version: '3.8'

services:
  mcp-server:
    build:
      context: ./mcp-okta-server
      dockerfile: Dockerfile
    container_name: mcp-okta-server
    ports:
      - "8001:8001"
    environment:
      # Override for Docker Compose - bind to all interfaces
      - MCP_SERVER_HOST=0.0.0.0
      - MCP_SERVER_PORT=8001
      - MCP_SERVER_URL=http://localhost:8001
      # Ensure uv cache directory is writable
      - UV_CACHE_DIR=/tmp/uv-cache
    env_file:
      - ./mcp-okta-server/.env  # For local development only
    healthcheck:
      test: ["CMD", "curl", "-f", "-H", "MCP-Protocol-Version: 2025-06-18", "http://localhost:8001/.well-known/oauth-protected-resource"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    networks:
      - mcp-network

  mcp-client:
    build:
      context: ./mcp-okta-client
      dockerfile: Dockerfile
    container_name: mcp-okta-client
    depends_on:
      mcp-server:
        condition: service_healthy
    environment:
      - MCP_SERVER_URL=http://mcp-server:8001/mcp
      # Ensure uv cache directory is writable
      - UV_CACHE_DIR=/tmp/uv-cache
    env_file:
      - ./mcp-okta-client/.env  # For local development only
    profiles:
      - client  # Use: docker-compose --profile client up
    networks:
      - mcp-network

networks:
  mcp-network:
    driver: bridge